### ISSUE TITLE
Create universal login function 

### ISSUE THREAD

**Issue by chavarera** [Python-World/s-tool#26]
Task
- accept username and password.
- perform login and return logged in page result

**Comment by MuditCh57** [comment]
Hey I'd like to contribute. But I've some doubts. Could you please explain more what I need to do. 
I think I just have to make a basic function which performs login. Correct me If I am wrong. 🙌

**Comment by chavarera** [comment]
@MuditCh57 you are right

consider any login form which accept username and password and need to click on submit (type) button


or

Create a function which can accept login form name and fill form and submit it

**Comment by MuditCh57** [comment]
I don't know how to fill a form with help of python. I thought I've to make a simple function which takes name, password and checks with correct name, password. So it bit difficult for me.

**Comment by chavarera** [comment]
@MuditCh57 

I have separated subtask it will help you to achieve login goal

1. Function accept driver, login page URL, and set of parameters to be get filled
2. based on parameter fill information using fill method which is available in utils.py file
3. Click on login, submit or a given input element

**Comment by chavarera** [comment]
@MuditCh57 are you working on it?

**Comment by MuditCh57** [comment]
Can I do it after 27 July because my exams are going on?

**Comment by MuditCh57** [comment]
Hey, @chavarera I'm sorry. I am not working on this anymore. 
Thanks.

**Comment by chavarera** [comment]
ok @MuditCh57
