### ISSUE TITLE
Avoid default mutable arguments

### ISSUE THREAD

**Issue by chavarera** [Python-World/s-tool#27]
https://github.com/Python-World/s-tool/blob/7a5651a1b2277a2f02363cde5469325dc072d814/s_tool/parser.py#L5

**Comment by svenkat19** [comment]
I'd like to work on this

**Comment by chavarera** [comment]
sure @svenkat19

**Comment by svenkat19** [comment]
I guess only one mutable argument hadn't been changed across all the files I went through
