### ISSUE TITLE
add functionality to wait till element loaded

### ISSUE THREAD

**Issue by chavarera** [Python-World/s-tool#30]
add functionality for driver  to wait till element loaded

**Comment by supersonic1999** [comment]
Hi, i'm looking into this issue.

Can you explain more please?

**Comment by supersonic1999** [comment]
I see the issue now. In utils.py there is "WebDriverWait" this will wait for 2 seconds if the element hasn't loaded.
The issue with this is that if the element doesn't exist also it will 2 wait 2 seconds. 

There needs to be a global bPageLoaded bool somewhere or a check.

Also i think get_element doesnt wait at all.

**Comment by chavarera** [comment]
> I see the issue now. In utils.py there is "WebDriverWait" this will wait for 2 seconds if the element hasn't loaded.
> The issue with this is that if the element doesn't exist also it will wait 2 seconds.
> 
> There needs to be a global bPageLoaded bool somewhere or a check.
> 
> Also i think get_element doesnt wait at all.

right :+1:
