### ISSUE TITLE
Check page loaded or not 

### ISSUE THREAD

**Issue by chavarera** [Python-World/s-tool#31]
Check whether the page is loaded or not

Note: you can use javascript and check the state of page

**Comment by SugatoBagchi** [comment]
Hi, 

I would like to work on this issue. Can you please tell me what to do after I check the state of the page?

**Comment by chavarera** [comment]
@SugatoBagchi return a boolean status only

**Comment by SugatoBagchi** [comment]
Ok, I would like to work on this issue @chavarera!

Can you please tell me, how to get started and where I can add that JavaScript function?

**Comment by chavarera** [comment]
1. Create functions inside utils.py
2. Create partial function insider driver class
3. write testcase

**Comment by chavarera** [comment]
@SugatoBagchi Are you working on it?
