### ISSUE TITLE
retrieve webpage title

### ISSUE THREAD

**Issue by chavarera** [Python-World/s-tool#47]
**Is your feature request related to a problem? Please describe.**
Retrieve web  page title

**Comment by rashidkalwar** [comment]
In which file should I write the code, I will be using python requests and bs4 so I also be adding a few dependencies as well.

**Comment by chavarera** [comment]
@rashidkalwar 

1. create utils functions
2. and add method into driver.py

code should be written in selenium only

**Comment by chavarera** [comment]
@rashidkalwar have you got idea?

**Comment by rashidkalwar** [comment]
@chavarera yes I have everything, I can just use a webdriver to access a page and retrieve the title, sorry for delay as I am also working on several different projects, I will hopefully make a PR tomorrow.

thanks!

**Comment by chavarera** [comment]
@rashidkalwar cool :small_airplane:  :smile:

**Comment by rashidkalwar** [comment]
Just made a PR, please check I have added a function just as you wanted, check it and if there needs to be something changed please let me know.
