### ISSUE TITLE
The name stool is already occupied on PyPI

### ISSUE THREAD

**Issue by aahnik** [Python-World/s-tool#7]
We want to distribute our package on PyPI. But this name is already occupied by another person 

https://pypi.org/project/stool/

we need to rename our project

**Comment by chavarera** [comment]
can we use **s-tool**

or any suggestion?

**Comment by aahnik** [comment]
Yup! s-tool will be fine. Let's not waste energy trying to think of a perfect name. 

I am going with `s-tool` in pyproject.toml and other places.

**Comment by aahnik** [comment]
I have reserved `s-tool` on PyPI.  If you want I can transfer the package to your PyPI account.

Or we may use github actions to publish to PyPI (whenever a new release is published). In that case I will share the upload token, and you can set it in github secrets.

**Comment by chavarera** [comment]
@aahnik  ok
