### ISSUE TITLE
parse table structure

### ISSUE THREAD

**Issue by chavarera** [Python-World/s-tool#9]
write a parser function to parse the table data into list of list .

**Comment by chavarera** [comment]
@aahnik you can use HTML template for testing result

[html_file](https://github.com/Python-World/s-tool/blob/main/tests/index.html)

**Comment by aahnik** [comment]
hi @chavarera, sorry, I am going away from GitHub for a few months. (for exams)

this is a wonderful project. I will contribute when I come back. in the meantime, others in the community will carry on the work.

**Comment by chavarera** [comment]
@aahnik sure thanks
